myfile=open("textonormal.txt", "rt")
textocompleto = myfile.read()
myfile.close()
textosinw=textocompleto.replace("W", "")
textosiny=textocompleto.replace("Y","")
textosinf=textocompleto.replace("F","")
numerow=len(textocompleto)-len(textosinw)
numeroy=len(textocompleto)-len(textosiny)
numerof=len(textocompleto)-len(textosinf)
print("W: " + str(numerow) + "\n")
print("Y: " + str(numeroy) + "\n")
print("F: " + str(numerof) + "\n")
CEM=5600*numerow+1350*numeroy+200*numerof+17*125
print("Coeficiente de extinción molar teórico de la BSA a 280 nm: " + str(CEM) + " M^-1*cm^-1")
